#!/bin/bash
#export ACCESS_API=http://127.0.0.1:8080
export ACCESS_API=https://access-testnet.onflow.org
export WALLET_DISCOVERY=https://fcl-discovery.onflow.org/testnet/authn
export FT_CONTRACT=0xee82856bf20e2aa6
export FUSD_CONTRACT=0xe223d8a629e49c68
export SENTIMEN_CONTRACT=0xf21fee1faa18dce2
export SENTIMENMETADATA_CONTRACT=0xf21fee1faa18dce2
export NFTSTOREFRONT_CONTRACT=0xf21fee1faa18dce2
export MARKETPLACE_CONTRACT=0xf21fee1faa18dce2


export REACT_APP_ACCESS_NODE=${ACCESS_API}
export REACT_APP_WALLET_DISCOVERY=${WALLET_DISCOVERY}
export REACT_APP_FT_CONTRACT=${FT_CONTRACT}
export REACT_APP_FUSD_CONTRACT=${FUSD_CONTRACT}
export REACT_APP_SENTIMEN_CONTRACT=${SENTIMEN_CONTRACT}
export REACT_APP_SENTIMENMETADATA_CONTRACT=${SENTIMENMETADATA_CONTRACT}
export REACT_APP_NFTSTOREFRONT_CONTRACT=${NFTSTOREFRONT_CONTRACT}
export REACT_APP_MARTKETPLACE_CONTRACT=${MARKETPLACE_CONTRACT}


npm run start